Repository umccr/orca-ui, pull requests merged in 2024-12, with the labels that each got.

#90 Feat: Refine File Table/Page
  src/components/common/dropdowns/Dropdown.tsx
  src/components/dialogs/SimpleDialog.tsx
  src/components/files/ImageViewer.tsx
  src/components/files/igv/IgvJs.tsx
  src/modules/files/components/FileAPITable.tsx
  src/modules/files/components/FilePreviewDrawer.tsx
  src/modules/files/pages/files.tsx
  src/modules/lab/pages/library/LibraryWorkflow.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunTimeline.tsx
Labels: feature

#91 timeline and comment module in sequence runs
  src/api/sequenceRun.ts
  src/api/types/sequence-run.d.ts
  src/components/common/buttons/Button.tsx
  src/components/common/timelines/Timeline.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunDetailsDrawer.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunTable.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunTimeline.tsx
Labels: feature

#93 hotfix for api change
  src/api/types/sequence-run.d.ts
  src/api/types/workflow.d.ts
  src/api/workflow.ts
  src/modules/runs/components/workflowRuns/WorkflowRunFilterHeader.tsx
Labels: fix

#94 Feat: Enhance API List Filtering
  src/api/types/file.d.ts
  src/api/types/metadata.d.ts
  src/components/tables/Table.tsx
  src/modules/files/components/InputBadgeBox.tsx
  src/modules/files/pages/files.tsx
  src/modules/lab/components/library/LibraryTableFilter.tsx
  src/modules/lab/components/sample/SampleTableFilter.tsx
  src/modules/lab/components/subject/SubjectListAPITable.tsx
  src/modules/lab/components/subject/SubjectTableFilter.tsx
  src/modules/lab/components/subject/utils.tsx
  src/modules/lab/components/utils.tsx
Labels: feature

#95 chore: Remove temporary workaround for `orcabus_id` prefix
  src/components/layouts/lab/components/LibrarySideNavBar.tsx
  src/modules/lab/components/library/LibraryAnalysisReportTable.tsx
  src/modules/lab/components/library/PortalRunIdDropdown.tsx
  src/modules/lab/components/library/WorkflowVersion.tsx
  src/modules/lab/pages/library/LibraryOverview.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunTable.tsx
Labels: refactor
