Repository umccr/orca-ui, pull requests merged in 2024-10, with the labels that each got.

#38 Fix Metadata API component
  package.json
  src/api/metadata.ts
  src/api/types/metadata.d.ts
  src/components/common/dropdowns/PopoverDropdown.tsx
  src/components/layouts/lab/components/LibraryBreadCrumb.tsx
  src/components/navigation/tabs/ContentTabs.tsx
  src/components/tables/Table.tsx
  src/modules/lab/components/file/FileDownloadButton.tsx
  src/modules/lab/components/file/FilePreviewDrawer.tsx
  src/modules/lab/components/file/FileTable.tsx
  src/modules/lab/components/individual/IndividualListAPITable.tsx
  src/modules/lab/components/individual/IndividualTableFilter.tsx
  src/modules/lab/components/library/LibraryListAPITable.tsx
  src/modules/lab/components/library/LibraryTableDetails.tsx
  src/modules/lab/components/library/LibraryTableFilter.tsx
  src/modules/lab/components/library/PortalRunIdDropdown.tsx
  src/modules/lab/components/library/WorkflowVersion.tsx
  src/modules/lab/components/sample/SampleListAPITable.tsx
  src/modules/lab/components/sample/SampleTableFilter.tsx
  src/modules/lab/components/subject/SubjectListAPITable.tsx
  src/modules/lab/components/subject/SubjectTableFilter.tsx
  src/modules/lab/index.tsx
  src/modules/lab/metadata/components/LibraryAPITable.tsx
  src/modules/lab/metadata/components/MetadataTable.tsx
  src/modules/lab/metadata/components/SubjectAPITable.tsx
  src/modules/lab/metadata/index.tsx
  src/modules/lab/pages/Metadata.tsx
  src/modules/lab/pages/library/LibraryOverview.tsx
  src/modules/lab/pages/library/LibraryWorkflow.tsx
  src/modules/lab/routes.tsx
  src/modules/lab/subject/components/SubjectBasedLibraryTable.tsx
  src/modules/lab/subject/index.tsx
  src/router/modules.ts
  src/utils/navigation.ts
  yarn.lock
Labels: fix

#39 Fix Merge Conflict on Lab Component
  src/api/workflow.ts
  src/components/layouts/lab/components/LibrarySideNavBar.tsx
  src/modules/lab/components/library/PortalRunIdDropdown.tsx
  src/modules/lab/components/library/WorkflowVersion.tsx
  src/modules/lab/components/sample/SampleListAPITable.tsx
  src/modules/lab/pages/Metadata.tsx
Labels: fix

#43 Bugfix/reset paging parameters when filters changed
  src/hooks/useQueryParams.ts
Labels: bug

#46 Feat: File Browser Page
  src/components/common/dropdowns/Dropdown.tsx
  src/components/layouts/files/FilesLayout.tsx
  src/components/navigation/header/TokenDialog.tsx
  src/components/tables/Table.tsx
  src/modules/files/components/FileAPITable.tsx
  src/modules/files/components/FileDownloadButton.tsx
  src/modules/files/components/FilePreviewDrawer.tsx
  src/modules/files/pages/files.tsx
  src/modules/files/routes.tsx
  src/modules/lab/pages/library/LibraryWorkflow.tsx
  src/router/modules.ts
  src/utils/appURLs.ts
  src/utils/dayjs.ts
  src/utils/navigation.ts
Labels: feature

#45 Feat/refactor pipeline
  deploy/lambda/Dockerfile
  deploy/lambda/start_build.py
  deploy/lib/application-stack.ts
  deploy/lib/pipeline-stack.ts
Labels: feature

#47 File Overview Highlight
  src/api/file.ts
  src/api/metadata.ts
  src/api/workflow.ts
  src/components/common/error/DetailedErrorBoundary.tsx
  src/components/common/json-to-table/json-to-table.tsx
  src/components/layouts/lab/components/LibraryBreadCrumb.tsx
  src/components/tables/GroupedRowTable.tsx
  src/modules/files/components/FileAPITable.tsx
  src/modules/lab/components/individual/IndividualListAPITable.tsx
  src/modules/lab/components/library/LibraryAnalysisReportTable.tsx
  src/modules/lab/components/library/LibraryListAPITable.tsx
  src/modules/lab/components/library/LibraryTableDetails.tsx
  src/modules/lab/components/library/PortalRunIdDropdown.tsx
  src/modules/lab/components/sample/SampleListAPITable.tsx
  src/modules/lab/components/subject/SubjectListAPITable.tsx
  src/modules/lab/pages/library/LibraryOverview.tsx
  src/modules/lab/pages/library/LibraryWorkflow.tsx
  src/utils/constant.ts
Labels: feature

#49 Refine: Analysis table and Link s3 uri to `/files` page
  src/components/common/json-to-table/json-to-nested-list.tsx
  src/modules/files/components/FileAPITable.tsx
  src/modules/files/pages/files.tsx
  src/modules/lab/components/library/LibraryAnalysisReportTable.tsx
  src/modules/runs/workflowRuns/components/StatusTimeline.tsx
Labels: feature

#50 Feat: Metadata OrcabusId and Library History
  src/api/metadata.ts
  src/api/types/file.d.ts
  src/api/types/metadata.d.ts
  src/api/types/workflow.d.ts
  src/components/layouts/lab/components/LibraryBreadCrumb.tsx
  src/components/layouts/lab/components/LibrarySideNavBar.tsx
  src/components/tables/Table.tsx
  src/modules/lab/components/library/LibraryAnalysisReportTable.tsx
  src/modules/lab/components/library/LibraryListAPITable.tsx
  src/modules/lab/components/library/LibraryTableDetails.tsx
  src/modules/lab/components/library/PortalRunIdDropdown.tsx
  src/modules/lab/components/library/WorkflowVersion.tsx
  src/modules/lab/pages/library/LibraryHistory.tsx
  src/modules/lab/pages/library/LibraryOverview.tsx
  src/modules/lab/pages/library/LibraryWorkflow.tsx
  src/modules/lab/routes.tsx
  src/modules/runs/workflowRuns/components/WorkflowRunDetailsDrawer.tsx
Labels: feature

#48 refactor pipeline for share source code sequentially for each stage
  deploy/config.ts
  deploy/lambda/env_config.py
  deploy/lambda/start_build.py
  deploy/lib/application-stack.ts
  deploy/lib/pipeline-stack.ts
  deploy/package.json
  deploy/yarn.lock
  index.html
  package.json
  public/env.js
  src/api/_mock/workflowpayloadfile.json
  src/config.ts
  src/modules/auth/SignInPage.tsx
  src/utils/commonUtils.ts
  tsconfig.app.json
  tsconfig.json
  tsconfig.vite.json
  vite.config.ts
  yarn.lock
Labels: feature

#52 workflow runs module update from api update
  src/api/types/workflow.d.ts
  src/api/workflow.ts
  src/components/common/datepicker/DateRangePicker.tsx
  src/modules/runs/workflowRuns/components/WorkflowRunDetailsDrawer.tsx
  src/modules/runs/workflowRuns/components/WorkflowRunFilterHeader.tsx
  src/modules/runs/workflowRuns/components/WorkflowRunTable.tsx
Labels: fix

#60 replace library with orcabusId in lib links
  src/modules/runs/components/workflowRuns/WorkflowRunDetailsTable.tsx
Labels: bug

#62 fix ui format bugs for timeline and payload
  src/components/common/badges/Badge.tsx
  src/components/common/json-to-table/json-display.tsx
  src/components/common/timelines/Timeline.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunTimeline.tsx
Labels: fix
