Repository umccr/orca-ui, pull requests merged in 2024-11, with the labels that each got.

#58 Feat: Add Trigger Sync Metadata Page
  src/api/metadata.ts
  src/api/types/metadata.d.ts
  src/components/layouts/lab/LibraryLayout.tsx
  src/components/layouts/lab/components/LibraryBreadCrumb.tsx
  src/components/navigation/breadcrumbs/index.tsx
  src/components/navigation/navbar/ModuleNavBar.tsx
  src/modules/lab/components/subject/SubjectListAPITable.tsx
  src/modules/lab/pages/Metadata.tsx
  src/modules/lab/pages/Sync.tsx
  src/modules/lab/routes.tsx
Labels: feature

#64 Fix: Library Layout CSS
  src/components/layouts/lab/LibraryLayout.tsx
Labels: fix

#66 Fix/codepipeline manualapprove sequecing
  deploy/lib/pipeline-stack.ts
Labels: fix

#67 Chore: Upgrade Dependencies
  .pre-commit-config.yaml
  package.json
  src/api/_mock/mockDataTransfer.ts
  src/api/_mock/mockWorkflowRunData.ts
  src/api/utils.ts
  src/components/common/buttons/ButtonGroup.tsx
  src/components/diagrams/WorkflowDiagram.tsx
  src/components/files/igv/IgvDesktop.tsx
  src/components/layouts/lab/LibraryLayout.tsx
  src/components/navigation/header/index.tsx
  tailwind.config.js
  yarn.lock
Labels: refactor

#77 Chore: Fix Miscellaneous Styling
  index.html
  src/components/common/dropdowns/Dropdown.tsx
  src/components/common/json-to-table/json-to-table.tsx
  src/components/files/igv/IgvJs.tsx
  src/components/layouts/MainLayout.tsx
  src/components/layouts/lab/LibraryLayout.tsx
  src/components/layouts/lab/SubjectLayout.tsx
  src/components/navigation/breadcrumbs/index.tsx
  src/components/navigation/header/index.tsx
  src/components/navigation/navbar/ModuleNavBar.tsx
  src/components/navigation/navbar/SideNavBar.tsx
  src/modules/lab/components/contact/utils.tsx
  src/modules/lab/components/library/LibraryAnalysisReportTable.tsx
  src/modules/lab/components/library/LibraryTableDetails.tsx
  src/modules/lab/pages/Metadata.tsx
  src/modules/lab/pages/library/LibraryOverview.tsx
  src/modules/lab/routes.tsx
Labels: fix, refactor

#70 Fix/auto redirect to main domain
  src/context/AmplifyAuthContext.tsx
Labels: fix

#79 Fix/UI fix and refactor
  index.html
  src/components/layouts/MainLayout.tsx
  src/components/layouts/runs/RunsPageLayout.tsx
  src/components/navigation/navbar/SideNavBar.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunTable.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunDetailsTable.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunTable.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunTimeline.tsx
  src/modules/runs/index.tsx
  src/styles/main.css
Labels: fix

#81 Feat: Update File Viewer Constrain
  src/components/files/index.tsx
  src/modules/files/components/FilePreviewDrawer.tsx
  src/modules/lab/components/library/LibraryTableDetails.tsx
Labels: feature

#88 Fix: Project Based Library Filter
  src/api/types/metadata.d.ts
  src/api/types/workflow.d.ts
  src/modules/lab/components/library/LibraryTableFilter.tsx
  src/modules/lab/components/project/ProjectTableFilter.tsx
  src/modules/lab/components/sample/SampleTableFilter.tsx
  src/modules/lab/components/subject/SubjectTableFilter.tsx
Labels: fix

#89 Feat: Link Library to WFR
  src/components/navigation/tabs/ContentTabs.tsx
  src/components/navigation/tabs/LinkTabs.tsx
  src/components/tables/Table.tsx
  src/modules/lab/components/library/LibraryAnalysisReportTable.tsx
  src/modules/lab/components/library/LibraryTableDetails.tsx
  src/modules/lab/pages/Metadata.tsx
  src/modules/lab/pages/library/LibraryOverview.tsx
  src/modules/lab/pages/library/LibraryWorkflow.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunTable.tsx
Labels: feature
