Repository umccr/orca-ui, pull requests merged in 2024-09, with the labels that each got.

#23 hotfix for deploy bug and testing
  deploy/lib/application-stack.ts
  deploy/lib/pipeline-stack.ts
  package.json
  src/main.tsx
  start.sh
  vite.config.ts
  yarn.lock
Labels: bug

#24 refactore some context before next commit and fix dependabot issue
  deploy/package.json
  deploy/yarn.lock
  src/App.tsx
  src/components/navigation/header/index.tsx
  src/context/AmplifyAuthContext.tsx
  src/context/QueryClientContext.tsx
  src/context/UserContext.tsx
  src/main.tsx
  src/modules/auth/SignInPage.tsx
  src/router/index.tsx
Labels: feature

#25 Feat: Enhancement
  src/components/common/spinner/SpinnerWithText.tsx
  src/components/dialogs/SimpleDialog.tsx
  src/components/files/index.tsx
  src/components/layouts/MainLayout.tsx
  src/components/layouts/lab/LibraryLayout.tsx
  src/components/navigation/header/index.tsx
  src/components/navigation/navbar/SideNavBar.tsx
  src/components/tables/Pagination.tsx
  src/components/tables/Table.tsx
  src/hooks/useQueryParams.ts
  src/modules/lab/library/workflow/components/PortalRunIdDropdown.tsx
  src/modules/lab/library/workflow/components/WorkflowVersion.tsx
  src/modules/lab/library/workflow/index.tsx
  src/modules/lab/metadata/components/LibraryAPITable.tsx
  src/modules/lab/metadata/components/MetadataFilterDropdown.tsx
  src/modules/lab/metadata/components/MetadataTable.tsx
  src/modules/lab/metadata/components/SubjectAPITable.tsx
Labels: fix

#31 fix the side drawer flash issue and upgrade some ui
  src/components/common/datepicker/DateRangePicker.tsx
  src/components/common/drawers/sideDrawer.tsx
  src/components/common/select/IconMultipleSelect.tsx
  src/components/common/tooltips/index.tsx
  src/context/AmplifyAuthContext.tsx
  src/modules/runs/components/StatusTimeline.tsx
  src/modules/runs/components/WorkflowRunDetailsDrawer.tsx
  src/modules/runs/components/WorkflowRunTable.tsx
  src/modules/runs/components/WorkflowRunTableHeader.tsx
  src/modules/runs/tables/WorkflowRunTable.tsx
  src/utils/commonUtils.ts
Labels: bug, fix
