Repository umccr/orca-ui, pull requests merged in 2025-02, with the labels that each got.

#111 Fix: Lab Library Layout
  src/components/layouts/lab/components/LibrarySideNavBar.tsx
  src/components/navigation/navbar/ModuleNavBar.tsx
Labels: fix

#113 update deploy dependents for security alerts
  deploy/package.json
  deploy/yarn.lock
Labels: fix

#114 update deploy dependents for security alerts
  deploy/package.json
  deploy/yarn.lock
Labels: fix

#115 fix build error and warnings
  src/components/common/badges/Badge.tsx
  src/components/common/badges/StatusBadge.tsx
  src/components/common/badges/index.tsx
  src/main.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunTimeline.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunTimeline.tsx
  src/modules/runs/index.tsx
  src/utils/navigation.ts
  src/utils/statusUtils.ts
  vite.config.ts
Labels: fix

#116 Fix/fix build error and warning
  deploy/lib/pipeline-stack.ts
  src/modules/runs/index.tsx
Labels: fix

#121 Feat: extra igv desktop button
  src/components/files/igv/IgvDesktop.tsx
  src/components/files/igv/IgvJs.tsx
  src/modules/files/components/FileAPITable.tsx
Labels: feature

#124 Fix: Unused Variables
  src/components/common/sidebar/SideBar.tsx
  src/components/common/sidebar/SideBarLayout.tsx
Labels: fix

#123 add action button for qc report link
  src/modules/runs/components/sequenceRuns/SequenceRunTable.tsx
Labels: feature

#126 Chore: CSS and Miscellaneous Updates
  src/api/workflow.ts
  src/components/common/dialogs/SimpleDialog.tsx
  src/components/common/json-to-table/json-to-table.tsx
  src/components/common/tooltips/index.tsx
  src/components/layouts/lab/LibraryLayout.tsx
  src/components/navigation/breadcrumbs/index.tsx
  src/components/tables/GroupedRowTable.tsx
  src/modules/files/components/FileAPITable.tsx
  src/modules/files/components/InputBadgeBox.tsx
  src/modules/lab/components/library/LibraryAnalysisReportTable.tsx
  src/modules/lab/components/library/LibraryTableDetails.tsx
  src/modules/lab/components/library/PortalRunIdDropdown.tsx
  src/modules/lab/components/library/WorkflowDialogDetail.tsx
  src/modules/lab/pages/library/LibraryWorkflow.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunDetailsTable.tsx
Labels: refactor

#128 Feat (srm) modify multiqc report link
  src/components/icons/MultiqcIcon.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunTable.tsx
Labels: refactor

#133 Feat: Expand metadata search
  .gitignore
  package.json
  src/components/common/json-to-table/json-to-table.tsx
  src/components/common/search/Search.tsx
  src/components/layouts/lab/LibraryLayout.tsx
  src/components/layouts/lab/components/LibraryBreadCrumb.tsx
  src/modules/files/components/FileAPITable.tsx
  src/modules/files/pages/files.tsx
  src/modules/lab/components/individual/IndividualListAPITable.tsx
  src/modules/lab/components/individual/IndividualTableFilter.tsx
  src/modules/lab/components/library/LibraryAnalysisReportTable.tsx
  src/modules/lab/components/library/LibraryListAPITable.tsx
  src/modules/lab/components/library/LibraryTableDetails.tsx
  src/modules/lab/components/library/LibraryTableFilter.tsx
  src/modules/lab/components/library/PortalRunIdDropdown.tsx
  src/modules/lab/components/project/ProjectListAPITable.tsx
  src/modules/lab/components/project/ProjectTableFilter.tsx
  src/modules/lab/components/sample/SampleListAPITable.tsx
  src/modules/lab/components/sample/SampleTableFilter.tsx
  src/modules/lab/components/subject/SubjectListAPITable.tsx
  src/modules/lab/components/subject/SubjectTableFilter.tsx
  src/modules/lab/components/subject/utils.tsx
  src/modules/lab/pages/Metadata.tsx
  src/modules/runs/components/analysisRuns/AnalysisRunDetailsWorkflowRuns.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunTable.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunTable.tsx
Labels: feature

#134 Fix: add theme setting exception when authentication state
  src/context/AmplifyAuthContext.tsx
Labels: bug

#135 Fix: Bug Fix on Dropdown Portal Run Id
  src/modules/lab/components/library/LibraryAnalysisReportTable.tsx
Labels: fix

#127 refactor workflow deatils page
  .gitignore
  .storybook/main.ts
  .storybook/preview.ts
  src/api/workflow.ts
  src/components/common/accordion/Accordion.tsx
  src/components/common/accordion/AccordionList.tsx
  src/components/common/accordion/index.tsx
  src/components/common/buttons/ButtonGroup.tsx
  src/components/common/buttons/IconButton.tsx
  src/components/common/dialogs/SimpleDialog.tsx
  src/components/common/dropdowns/IconDropdown.tsx
  src/components/common/json-to-table/json-display.tsx
  src/components/common/json-to-table/json-to-nested-list.tsx
  src/components/common/search/Search.tsx
  src/components/common/select/IconMultipleSelect.tsx
  src/components/common/select/SearchableSelect.tsx
  src/components/common/select/index.tsx
  src/components/common/sidebar/SideBar.tsx
  src/components/common/sidebar/SideBarLayout.tsx
  src/components/common/timelines/Timeline.tsx
  src/components/common/toaster/index.tsx
  src/components/common/tooltips/index.tsx
  src/components/icons/MultiqcIcon.tsx
  src/components/icons/RedirectIcon.tsx
  src/components/layouts/lab/components/LibraryDetailBar.tsx
  src/components/layouts/runs/RunsModuleLayout.tsx
  src/components/navigation/tabs/ContentTabs.tsx
  src/components/tables/Table.tsx
  src/modules/lab/components/individual/IndividualListAPITable.tsx
  src/modules/lab/components/library/LibraryListAPITable.tsx
  src/modules/lab/components/library/WorkflowDialogDetail.tsx
  src/modules/lab/components/library/WorkflowVersion.tsx
  src/modules/lab/components/project/ProjectListAPITable.tsx
  src/modules/lab/components/sample/SampleListAPITable.tsx
  src/modules/lab/components/subject/SubjectListAPITable.tsx
  src/modules/runs/components/analysisRuns/AnalysisRunDetailsWorkflowRuns.tsx
  src/modules/runs/components/analysisRuns/AnalysisRunFilterHeader.tsx
  src/modules/runs/components/common/CommentDialog.tsx
  src/modules/runs/components/common/RerunDialog.tsx
  src/modules/runs/components/common/StatesDialog.tsx
  src/modules/runs/components/common/UserProfileSection.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunDetailsDrawer.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunFilterHeader.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunTable.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunTimeline.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunContext.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunDetailsHeader.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunDetailsLinkage.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunDetailsSidebar.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunDetailsTable.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunFilterHeader.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunTimeline.tsx
  src/modules/runs/index.tsx
  src/modules/runs/pages/WorkflowRunsDetails.tsx
  src/stories/Select.stories.tsx
  src/styles/main.css
  src/utils/uriLinkFormatter.tsx
  tsconfig.app.json
Labels: refactor

#137 fix typecheck error in storybook
  src/components/common/checkbox/Checkbox.tsx
  src/stories/Button.stories.tsx
  src/stories/Charts.stories.tsx
  src/stories/Header.stories.tsx
  src/stories/Tables.stories.tsx
  src/stories/Tooltips.stories.tsx
  src/stories/_mock/mockScatterPlotData.ts
Labels: fix

#138 Feat: Upgrade CodePipeline V2
  deploy/lib/pipeline-stack.ts
Labels: feature

#140 Fix: Table Header Name
  src/modules/lab/components/contact/utils.tsx
  src/modules/lab/components/project/ProjectListAPITable.tsx
Labels: fix
