Repository umccr/orca-ui, pull requests merged in 2025-03, with the labels that each got.

#146 Fix: SASH Filter
  src/modules/lab/components/library/LibraryAnalysisReportTable.tsx
Labels: fix

#139 Sequence run detail & Rerun page refactor
  package.json
  src/api/sequenceRun.ts
  src/api/workflow.ts
  src/components/common/accordion/Accordion.tsx
  src/components/common/dialogs/SimpleDialog.tsx
  src/components/common/drawers/SideDrawer.tsx
  src/components/common/timelines/Timeline.tsx
  src/components/navigation/tabs/ContentTabs.tsx
  src/components/tables/ListTable.tsx
  src/components/tables/index.tsx
  src/modules/runs/components/common/FileViewDialog.tsx
  src/modules/runs/components/common/RNASUMSelect.tsx
  src/modules/runs/components/common/RerunDialog.tsx
  src/modules/runs/components/common/StateDialog.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunContext.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunDetailsActions.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunDetailsDrawer.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunDetailsHeader.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunDetailsLinkage.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunDetailsSidebar.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunFilterHeader.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunSampleSheetViewer.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunTable.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunTimeline.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunWorkflowRuns.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunWorkflowRunsStats.tsx
  src/modules/runs/components/sequenceRuns/SequenceRundetailsTimeline.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunContext.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunDetailsHeader.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunDetailsSidebar.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunFilterHeader.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunTimeline.tsx
  src/modules/runs/index.tsx
  src/modules/runs/pages/SequenceRunDetails.tsx
  src/modules/runs/pages/SequenceRunDetailsPage.tsx
  src/modules/runs/pages/SequenceRunSampleSheet.tsx
  src/modules/runs/pages/SequenceRunWorkflowRuns.tsx
  src/utils/commonUtils.ts
  src/utils/constant.ts
  src/utils/rnasumUtils.ts
  src/utils/samplesheetUtils.ts
  yarn.lock
Labels: feature, refactor

#150 Fix/srm experimentname
  src/modules/runs/components/sequenceRuns/SequenceRunTable.tsx
Labels: fix

#153 fix bugs in srm state and samplesheet
  src/components/common/sidebar/SideBar.tsx
  src/components/tables/ListTable.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunDetailsActions.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunDetailsHeader.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunSampleSheetViewer.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunWorkflowRunsStats.tsx
  src/modules/runs/components/sequenceRuns/SequenceRundetailsTimeline.tsx
  src/modules/runs/components/workflowRuns/WorkflowRunDetailsHeader.tsx
  src/modules/runs/pages/SequenceRunSampleSheet.tsx
Labels: fix

#157 SRM workflowruns linking bugs fix
  src/modules/runs/components/sequenceRuns/SequenceRunWorkflowRuns.tsx
  src/modules/runs/components/sequenceRuns/SequenceRunWorkflowRunsStats.tsx
  src/modules/runs/pages/SequenceRunSampleSheet.tsx
Labels: bug
